### PR TITLE
Error on IE8 & IE9 due to setting router location to history

### PR DESCRIPTION
**Pull request by andrewmp1**
Need to check properties on window.history to really detect if IE8 or IE9.

### CODE REVIEW

**Comment by digitaltoad** [comment]
The only problem with this is that copy pasted links won't work in all places.

**Comment by andrewmp1** [comment]
@digitaltoad there is probably more work to support browsers like IE8 & 9 cleanly than this fix for detecting history support.  IE8 & 9 error w/ a blank screen on embercasts w/ the current code from my quick test w/ virtual machines.  If there is an issue between hash and history links then maybe just taking out support for hash in the router and not supporting IE8 & 9 is a better solution?  This at least allows IE8 & 9 to load and use hash urls w/o throwing an error and getting a blank screen.

**Comment by digitaltoad** [comment]
Although probably not a desired long term solution, something like this could be a quick fix for the current codebase.

``` javascript
if (!history.pushState) {
  Ember.LinkView.reopen({
    click: function() {
      window.location.path.replace(this.get('href'));
    }
  });

  Ember.HistoryLocation.reopen({
    replaceState: function() {}
  });
}

App.Router.reopen({
  location: 'history'
});
```

**Comment by andrewmp1** [comment]
Wow, I didn't even think of that angle.  Should I update the pull request w/ this code instead?

**Comment by digitaltoad** [comment]
@ebryn, @machty what do you guys think?

**Comment by ebryn** [comment]
I personally don't care about supporting IE8 - it won't be able to play the videos since we're using the HTML5 video tag (and I don't want to bother with a Flash fallback). Fixing this for IE9 seems good, although I feel bad for anyone using IE9 :P

Should we be fixing this in Ember itself, rather than having hacks in our application?

**Comment by digitaltoad** [comment]
Its been said that we need a solution in Ember for this here https://github.com/emberjs/ember.js/pull/2685 which I totally agree with. I've been implementing hacks in my own apps for the same reasons.

**Comment by ebryn** [comment]
@Andrewmp1 can you update the PR with @digitaltoad's solution, or can you submit a PR @digitaltoad?

**Comment by andrewmp1** [comment]
I'll update this pull requests w/ digitaltoad's solution.

**Comment by andrewmp1** [comment]
I've updated the pull request w/ digitaltoad's workaround using history w/ IE9.

**Pull request merged**
